kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: caddy-ingress-controller
  labels:
    k8s-app: caddy-ingress-controller
  namespace: kube-system
spec:
  serviceName: caddy-ingress
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: caddy-ingress-controller
      namespace: kube-system
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: caddy-ingress-controller
          image: zikes/caddy-ingress:0.0.1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 12015
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 12015
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
          - containerPort: 12015
            hostPort: 12015
          - containerPort: 80
            hostPort: 80
          - containerPort: 443
            hostPort: 443
          volumeMounts:
            - name: tls-certificates-volume
              mountPath: /root/.caddy
          env:
            - name: ACME_EMAIL
              value: example@example.com
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
          - /caddy-ingress-controller
          - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
      volumes:
        - name: tls-certificates-volume
          persistentVolumeClaim:
            claimName: caddy-certs-claim
